### ISSUE TITLE
Positive and negative perturbations for monotonicity constraints

### ISSUE THREAD

**Issue by jkcshea** [a-torgovitsky/ivmte#1]
At the moment, we're just drawing the perturbations from something like a uniform distribution over $[0, 10^{-3}]$.
I think the perturbations $\varepsilon_k$ need to be both positive and negative.
We can let the distribution of these perturbations be an option.
But I thought I should confirm my thinking.

---------

**Question 1**

Let $m_d(x, u)$ denote the MTRs for $d = 0, 1$.
Suppose we think the MTRs should be increasing in $u$.
Originally, the corresponding constraint takes the form
(I'm going to ignore the slack variables and order the terms in a specific way for clarity)

$m_d(x, u_{k + 1}) - m_d(x, u_k) \ge 0$ for $u_k < u_{k+1}$.

When introducing the perturbations, we instead have

$m_d(x, u_{k + 1}) - m_d(x, u_k) \ge \varepsilon_k$ for $u_k < u_{k+1}$, and $\varepsilon_k$ drawn from some distribution.

Suppose we draw $\varepsilon_k$ uniformly over $[0, \overline{\varepsilon}]$, as in the write-up.
We are effectively imposing strict monotonicity.
How quickly the MTRs increase depends on
1. How large $\overline{\varepsilon}$ is
2. How coarse/fine the audit grid is

Cho and Russell (2023) says that $\varepsilon_k$ can be drawn from any continuous distribution with convex support.
It just needs to be independent of the data.
So should we draw from a distribution with negative and positive values?
E.g., $[-\overline{\varepsilon}, \overline{\varepsilon}]$.
This should (on average, I think) eliminate the problem above.

---------

**Question 2**

Suppose the user wants to impose constant MTEs.
Originally, this meant imposing the following:

$\text{MTE}(x, u_{k + 1}) - \text{MTE}(x, u_k) \ge 0$ for $u_k < u_{k+1}$ and
$\text{MTE}(x, u_{k + 1}) - \text{MTE}(x, u_k) \le 0$ for $u_k < u_{k+1}$.

With the perturbations, we now impose the following: 

$\text{MTE}(x, u_{k + 1}) - \text{MTE}(x, u_k) \ge \varepsilon_k$ for $u_k < u_{k+1}$ and
$\text{MTE}(x, u_{k + 1}) - \text{MTE}(x, u_k) \le \varepsilon_{k'}$ for $u_k < u_{k+1}$.

(notice that perturbations, $\varepsilon_k$ and $\varepsilon_{k'}$, are different across the two constraints).

1. I would think we need $\varepsilon_k = \varepsilon_{k'}$ to avoid infeasibility issues.
In the example above, this would arise if $\varepsilon_k > \varepsilon_{k'}$.
The slack variables should "absorb" these infeasibility issues.
But it seems strange to allow the perturbed constraints to be infeasible.

2. If the point above is valid, then perhaps we set $\varepsilon_k = \varepsilon_{k'}$.
Now suppose we draw $\varepsilon_k$ so that it is non-negative/non-positive, as in the write-up.
We are effectively imposing strict monotonicity of the MTEs, which is not what the user wants.
Again, how fast the MTE changes depends on how large $\varepsilon_k$ can be and how coarse/fine the audit grid is.

3. If the two previous points are valid, then maybe we set $\varepsilon_k = \varepsilon_{k'}$, and we draw $\varepsilon_k$ to have both positive and negative values.
Then we are imposing an almost-constant MTE.
This seems closer to what we want.

**Comment by a-torgovitsky** [comment]
>  I think the perturbations need to be both positive and negative.

Cho and Russell (and I think my note, unless I made a mistake) sets up everything as a $\leq 0$ inequality.
If that's the case, then we should only need positive perturbations, to make them $\leq +\varepsilon$. 
The idea is to relax the constraints.

I think that should address both your questions?
Let me know if I'm missing something though.

Q1: Relaxing the constraint of weak monotonicity would mean it can be somewhat non-monotone.
Q2: Relaxing the constraint of constant MTE just means it can be somewhat decreasing and/or somewhat increasing.

**Comment by jkcshea** [comment]
Ah okay, that is very helpful, thank you!
